// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe_0-sWtEq21G15lLa04eBQE7yS_X6dcU',
    appId: '1:115305552473:web:e101e14345b3eb55772f48',
    messagingSenderId: '115305552473',
    projectId: 'rasatara',
    authDomain: 'rasatara.firebaseapp.com',
    storageBucket: 'rasatara.firebasestorage.app',
    measurementId: 'G-9QWB00LXCQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD-HPVcjSSgzANBhkYiy1eTyRrbchwZVk',
    appId: '1:115305552473:android:c416763fc7351a6b772f48',
    messagingSenderId: '115305552473',
    projectId: 'rasatara',
    storageBucket: 'rasatara.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtIasUqsvL7KCG80_a-X90YAX5IWvb0OU',
    appId: '1:115305552473:ios:d7fe1f5dd652fa6a772f48',
    messagingSenderId: '115305552473',
    projectId: 'rasatara',
    storageBucket: 'rasatara.firebasestorage.app',
    iosBundleId: 'com.example.rasatara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtIasUqsvL7KCG80_a-X90YAX5IWvb0OU',
    appId: '1:115305552473:ios:d7fe1f5dd652fa6a772f48',
    messagingSenderId: '115305552473',
    projectId: 'rasatara',
    storageBucket: 'rasatara.firebasestorage.app',
    iosBundleId: 'com.example.rasatara',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCe_0-sWtEq21G15lLa04eBQE7yS_X6dcU',
    appId: '1:115305552473:web:a3af64076df8de65772f48',
    messagingSenderId: '115305552473',
    projectId: 'rasatara',
    authDomain: 'rasatara.firebaseapp.com',
    storageBucket: 'rasatara.firebasestorage.app',
    measurementId: 'G-F51H2HVHHX',
  );
}
